version: '3.9'

services:
  backend:
    build: ./backend
    container_name: alert-back
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: alert-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
    restart: unless-stopped
